// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntcsvockgohxhqpajsiq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50Y3N2b2NrZ29oeGhxcGFqc2lxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3ODQ3MTIsImV4cCI6MjA2OTM2MDcxMn0.0qjCkutpZjgIO14SZoKR5MM9jXbyyEiwpnXh58H5LrA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});